### ISSUE TITLE
Part IA and IB

### ISSUE THREAD

**Issue by ehawke2424** [camcribs/requests#14]
# **Module ID**
Dropbox w/ old notes, coursework etc

# **Describe what you will like to be uploaded**
https://www.dropbox.com/sh/kru9q9gigvexdbh/AADMG0hCI-nyUCBxKJjCIRNqa?dl=0

This link is floating around (eg on the Whatsapp group) and so should be accessible to everyone given the Whatsapp group limit capacity - would you be able to post it/link it? I feel like there was a Google Drive as well at some point but I don't fully remember

# Anything Else
....

**Comment by camcribs** [comment]
Maybe i'll add a useful links page to camcribs, but this won't come around until after the end of term probs

**Comment by camcribs** [comment]
Will close this issue, and may add the links in the future
