### ISSUE TITLE
3E6

### ISSUE THREAD

**Issue by ehawke2424** [camcribs/requests#15]
# **Module ID**
3E6

# **Describe what you will like to be uploaded**
Link to recorded lectures - https://drive.google.com/drive/folders/1PweQpjx4kSc7-ZmPzfjOxfnpoO4HJ6GO

# Anything Else
....

**Comment by ehawke2424** [comment]
The lecturer has been difficult w/ regards to lecture recordings (eg putting '7 day limits' on them or similar even if you have accessibility requirements) - someone shared these with me and so I'm passing them on

**Comment by camcribs** [comment]
Maybe i'll add a "useful links" page to camcribs, but this won't come around until after the end of term probs

**Comment by camcribs** [comment]
Will close this issue, and may add the links in the future
