### ISSUE TITLE
Bugs with 'Hub' Theme

### ISSUE THREAD

**Issue by wallace9320** [camcribs/requests#16]
CamCribs logo on top left not clickable in Hub theme
Title of block remains black on the paper selection screen after clicking a module (difficult to see), as in the following image
<img width="434" alt="image" src="https://user-images.githubusercontent.com/92096932/223099747-6ae5ac3f-4ce0-4cc6-b930-1dc382e6c7b2.png">

**Comment by camcribs** [comment]
hahah, I noticed these bugs but I cba to fix it when I made the theme. I'll fix it in a few days. Hub theme does seem to be quite popular

**Comment by camcribs** [comment]
aight its fixed
