### ISSUE TITLE
home screen databooks, and 3d8 datasheet

### ISSUE THREAD

**Issue by pmccart12** [camcribs/requests#20]
would u be able to add a 'databooks' button to the main home page alongside the already existing 'examples' and 'tripos' buttons? literally just for slightly quicker access to them.

also would u be able to add the 3d8 datasheet to the datasheets page as well?

thanks!!!:DD
[3D8 DataBook-Jan 2022.pdf](https://github.com/camcribs/requests/files/11069805/3D8.DataBook-Jan.2022.pdf)

**Comment by camcribs** [comment]
![image](https://user-images.githubusercontent.com/107072797/227801247-8f533097-6d6e-45df-a6f8-4ed0139f45cb.png)

Ive added a little databook button on the navbar, I think it looks better than having a databook button on the homepage
