### ISSUE TITLE
1P2

### ISSUE THREAD

**Issue by xli562** [camcribs/requests#26]
---
name: Update Requests
about: Request updates/uploads to modules
title: "[1P2]"
labels: enhancement
assignees: camcribs

---

# **1P2 Materials**

# **Describe what you will like to be uploaded**
Plz update EP and CRIBS for **EP3** in ** Materials, 1P2**

# Anything Else
Shercliff might have made changes to other EPs as well, in the 1P2 Materials course.

**Comment by camcribs** [comment]
duplicate
