### ISSUE TITLE
Improvement to Navigation Bar

### ISSUE THREAD

**Issue by lpender3672** [camcribs/requests#28]
![image](https://github.com/camcribs/requests/assets/58957722/5ad84115-8cf0-4912-9f6a-3557003f88bb)

The zoom-in and out buttons are occluded when opening papers.
I've tried multiple window sizes and it seems to always be aligned with the bottom of the pdf viewer. </br>

While we can scroll down and click it, can they be moved up so they aren't occluded when opening papers?

**Comment by camcribs** [comment]
Sorry for the late response, this is honestly a very minor issue and isn't worth my time atm to fix.
I suggest just using control + scroll wheel to zoom
If I get time, I  will try to see what I can do
Hope you can understand.
