### ISSUE TITLE
Feature request: Quick access to databook

### ISSUE THREAD

**Issue by k12ish** [camcribs/requests#7]
Thank you so much for CamCribs, it's been immensely useful to me,

Here's a mockup of what I'm thinking of:

![image](https://user-images.githubusercontent.com/45272873/212375056-ced0934d-feba-42be-ad01-f9880559308c.png)

I understand that it's almost the start of term, and there might be technical limitations behind this feature. Whatever your thoughts are, let me know!

**Comment by camcribs** [comment]
heya, I had an idea like this in the plans, it should be coming soon!!

**Comment by camcribs** [comment]
i have implemeted it for single view pages
